import type { SwipeProfile } from "./types";

export const SAMPLE_PROFILES: SwipeProfile[] = [
  {
    id: "maya-chen",
    name: "Maya Chen",
    age: 27,
    mode: "dating",
    gymLocation: "World Class",
    workoutFocus: "Bodybuilding",
    preferredTimeLabel: "Morning",
    preferredTimeRange: "07:00 – 09:00",
    bio: "PR on deadlifts last week. Looking for someone who counts macros AND dessert.",
    distanceKm: 3,
    verified: true,
    guaranteedMatch: true,
    photoGradient: "linear-gradient(155deg, #FF2A5F 0%, #7A1247 55%, #1A0510 100%)",
    initials: "MC",
  },
  {
    id: "jordan-reyes",
    name: "Jordan Reyes",
    age: 31,
    mode: "gym-buddy",
    gymLocation: "Stay Fit",
    workoutFocus: "Crossfit",
    preferredTimeLabel: "Evening",
    preferredTimeRange: "18:00 – 20:00",
    bio: "Need a spotter who won't bail on leg day. WODs > small talk.",
    distanceKm: 5,
    verified: true,
    photoGradient: "linear-gradient(155deg, #00F2FE 0%, #0B6B77 55%, #051217 100%)",
    initials: "JR",
  },
  {
    id: "priya-nair",
    name: "Priya Nair",
    age: 25,
    mode: "dating",
    gymLocation: "World Class",
    workoutFocus: "Padel",
    preferredTimeLabel: "Weekend",
    preferredTimeRange: "09:00 – 11:00",
    bio: "Padel courts on Saturdays, brunch after. Competitive but I'll still buy the coffee.",
    distanceKm: 8,
    photoGradient: "linear-gradient(155deg, #FF6690 0%, #6A1450 55%, #170512 100%)",
    initials: "PN",
  },
  {
    id: "diego-alvarez",
    name: "Diego Alvarez",
    age: 29,
    mode: "gym-buddy",
    gymLocation: "Iron Temple",
    workoutFocus: "Powerlifting",
    preferredTimeLabel: "Morning",
    preferredTimeRange: "06:00 – 08:00",
    bio: "5am alarm, no excuses. Looking for a training partner to chase a 200kg squat.",
    distanceKm: 2,
    verified: true,
    photoGradient: "linear-gradient(155deg, #33F5FE 0%, #0E5A66 55%, #041014 100%)",
    initials: "DA",
  },
  {
    id: "sofia-marin",
    name: "Sofia Marin",
    age: 28,
    mode: "dating",
    gymLocation: "Stay Fit",
    workoutFocus: "Crossfit",
    preferredTimeLabel: "Evening",
    preferredTimeRange: "17:30 – 19:30",
    bio: "Ring dips and red wine. Swipe right if you can keep up with both.",
    distanceKm: 6,
    photoGradient: "linear-gradient(155deg, #FF4D7D 0%, #831038 55%, #190309 100%)",
    initials: "SM",
  },
];
